services:
  postgres:
    container_name: postgres
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=oms'
      - 'POSTGRES_PASSWORD=s3cr3t'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - /c/tmp/oms:/var/lib/postgresql/data
    networks:
      oms-network:

  oms-service:
    container_name: oms-service
    image: oms:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_PROFILE: "docker"
      OMS_USERNAME: "admin"
      OMS_PASSWORD: "s3cr3t"
      OMS_HOST: "localhost"
      OMS_PORT: 5432
      OMS_DB_NAME: "oms"
      DELETE_EVENT_DURATION: 4000
      ACTUATOR_EXPOSED_ENDPOINTS: "health, modulith"
      SERVER_PORT: 8081
    depends_on:
        - postgres
    networks:
      oms-network:
    restart: unless-stopped

volumes:
  postgres:
networks:
  oms-network:
    driver: bridge