services:
  postgres:
    container_name: postgres
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=oms'
      - 'POSTGRES_PASSWORD=s3cr3t'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"

    volumes:
      - /c/tmp/postgres_modulith:/var/lib/postgresql/data
    networks:
      modulith-network:

  oms:
    container_name: oms
    image: oms:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/oms
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=s3cr3t
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - postgres

    networks:
      modulith-network:
    restart: unless-stopped

volumes:
  postgres:
networks:
  modulith-network:
    driver: bridge