services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=oms'
      - 'POSTGRES_PASSWORD=s3cr3t'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - /c/tmp/oms:/var/lib/postgresql/data

volumes:
  postgres: