spring:
  datasource:
    username: admin
    password: s3cr3t
    url: jdbc:postgresql://postgres:5432/oms
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  modulith:
    republish-outstanding-events-on-restart: false
  data:
    jdbc:
      dialect: postgresql

delete:
  event:
    duration: 5000

logging:
  level:
    org.springframework.modulith: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080