name: build push image for deployment
on:
  push:
    branches:
      - master

jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest
    env:
      ACTUATOR_ENDPOINTS: ${{ vars.ACTUATOR_EXPOSED_ENDPOINTS }}
    steps:
      - name: Get Source Code
        run: echo "Hey! I am printing something."
      - name: show host environment variable
        run: echo "actuator endpoint ${{ env.ACTUATOR_ENDPOINTS }}"