name: build push image for deployment
on:
  push:
    branches:
      - master

jobs:
  sample-job-section:
    environment: action
    runs-on: ubuntu-latest
    env:
      ACTUATOR_ENDPOINTS: ${{ vars.ACTUATOR_EXPOSED_ENDPOINTS }}
    steps:
      - name: Get Source Code
        run: echo "Hey! I am printing something."
      - name: show host environment variable
        run: echo "actuator endpoint ${{ env.ACTUATOR_ENDPOINTS }}"

  build-job-section:
    environment: action
    runs-on: ubuntu-latest

    container: postgres
    services:
      postgres:
        image: 'postgres:16.2'
        env:
          POSTGRES_DB: ${{ vars.OMS_DB_NAME }}
          POSTGRES_USER: ${{ secrets.OMS_USERNAME }}
          POSTGRES_PASSWORD: ${{ vars.OMS_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven
      - name: Output Info
        run: ls && mvn -version & ls /opt
      - name: Build with Maven
        run: mvn clean package -Dspring-boot.run.profiles=${{ vars.SPRING_PROFILE }}
      - name: List the Files
        run: ls target/**