name: build push image for deployment
on:
  push:
    branches:
      - master

jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest

    steps:
      - name: Get Source Code
        run: echo "Hey! I am printing something."